//! Network generation from a rule-based model.

use itertools::{chain, zip_eq};
use std::rc::Rc;
use union_find::{QuickUnionUf, UnionBySize, UnionFind};

use super::{core::*, model::*, net::*, ob_tm::*, prelude::*, ty::*};

/// Wrapper enum for the two kinds of terms in a model.
///
/// This enum exists because the algorithms to generate species or transitions
/// are essentially the same and thus can operate generically over this type
/// instead of being duplicated for each case.
#[derive(Clone, PartialEq, Eq)]
pub enum ModelTm {
    Pat(PatTm),
    Rule(RuleTm),
}

impl ModelTm {
    /// Deconstructor for [`Pat`](Self::Pat) variant.
    fn take_pattern(self) -> Option<PatTm> {
        match self {
            Self::Pat(tm) => Some(tm),
            Self::Rule(_) => None,
        }
    }

    /// Deconstructor for the [`Rule`](Self::Rule) variant.
    fn take_rule(self) -> Option<RuleTm> {
        match self {
            Self::Rule(tm) => Some(tm),
            Self::Pat(_) => None,
        }
    }

    /// Constructs a model term corresponding to an agent or basic rule.
    fn basic(model: &Model, name: Name, terms: Vec<MorTm>) -> Option<Self> {
        if model.has_agent(&name) {
            Some(ModelTm::Pat(model.agent_tm(name, terms)))
        } else if model.has_rule(&name) {
            Some(ModelTm::Rule(model.rule_tm(name, terms)))
        } else {
            None
        }
    }

    /// Constructs an application of the tensor product to a model term.
    fn tensor(tm: ModelTm) -> Self {
        match tm {
            ModelTm::Pat(p) => ModelTm::Pat(PatTm::tensor(p)),
            ModelTm::Rule(r) => ModelTm::Rule(RuleTm::tensor(r)),
        }
    }

    /// Constructs a list of model terms.
    fn list(terms: impl IntoIterator<Item = ModelTm>) -> Self {
        let terms = terms.into_iter().collect_vec();
        if terms.iter().any(|tm| matches!(tm, ModelTm::Rule(_))) {
            // If any term is a rule, promote them all to rules.
            let rules = terms
                .into_iter()
                .map(|tm| match tm {
                    ModelTm::Rule(r) => r,
                    ModelTm::Pat(p) => RuleTm { rule: p.clone(), lhs: p.clone(), rhs: p },
                })
                .collect_vec();
            ModelTm::Rule(RuleTm::list(rules))
        } else {
            // Otherwise, we have a list of patterns.
            let patterns = terms.into_iter().map(|tm| tm.take_pattern().unwrap());
            ModelTm::Pat(PatTm::list(patterns))
        }
    }

    /// Restricts the model term at free variables along a morphism term.
    fn restrict(&self, at: ObTm, along: MorTm) -> Self {
        match self {
            ModelTm::Pat(p) => ModelTm::Pat(p.clone().restrict(&at, along)),
            ModelTm::Rule(r) => ModelTm::Rule(r.clone().restrict(&at, along)),
        }
    }
}

/// Generates a reaction network from a rule-based model.
pub struct NetGenerator<'a> {
    /// Model to generate from.
    model: &'a Model,

    /// Index from flattened operation codomains to operation names.
    ///
    /// Note that operations are indexed on *all* unique permutations of their
    /// codomain's sorts.
    cod_index: HashMap<Vec<Name>, Vec<Name>>,
}

/// State maintained by search algorithm for network generation.
#[derive(Clone)]
struct SearchState {
    /// Current term.
    tm: ModelTm,

    /// Current list of free variables.
    interface: Vec<IntermediateVar>,

    /// Fresh variable names are generated by incrementing this counter.
    next_name: usize,

    /// Current partition of (indexes of) original list of free variables.
    ///
    /// Wrap the union find in `Rc` since we don't have to mutate it at each
    /// branch point, only when restricting along an operation of co-arity >= 2.
    uf: Rc<QuickUnionUf<UnionBySize>>,

    /// Set of free variables that have been seen but not substituted.
    seen: im::HashSet<Name>,
}

#[derive(Clone, Copy, Debug)]
struct IntermediateVar {
    name: Name,
    sort: Name,
    component: usize,
}

impl<'a> NetGenerator<'a> {
    /// Constructs a network generator for the given model.
    pub fn new(model: &'a Model) -> Self {
        let mut cod_index = HashMap::<_, Vec<_>>::new();
        for (name, _, cod) in model.signature().operations() {
            let sorts = cod.sorts();
            let n = sorts.len();
            for ordering in sorts.into_iter().permutations(n).unique() {
                cod_index.entry(ordering).or_default().push(name);
            }
        }
        Self { model, cod_index }
    }

    /// Generates a network from the model up to a specified size.
    pub fn net(&self, max_width: usize) -> Net {
        let (species, transitions): (Vec<_>, Vec<_>) = (1..=max_width)
            .flat_map(|n| {
                chain(self.model.agent_names(), self.model.rule_names())
                    .combinations_with_replacement(n)
            })
            .flat_map(|names| self.find(names))
            .partition_map(|tm| match tm {
                ModelTm::Pat(pat) => Either::Left(pat),
                ModelTm::Rule(rule) => Either::Right(rule),
            });

        let mut net = Net::new();
        for tm in species {
            net.add_species(tm);
        }
        println!("{net}");
        for rule in transitions {
            let src = rule.lhs.associate().factorize().collect_tensor();
            let tgt = rule.rhs.associate().factorize().collect_tensor();
            net.add_transition(rule.rule, &src, &tgt)
                .map_err(|tm| tm.to_string())
                .expect("Species should already be added");
        }
        net
    }

    /// Generates species from the model up to a specified size.
    ///
    /// For definition of *species*, see [`Net`].
    pub fn species(&self, max_agents: usize) -> impl Iterator<Item = PatTm> {
        (1..=max_agents)
            .flat_map(|n| self.model.agent_names().combinations_with_replacement(n))
            .flat_map(|agents| self.find(agents))
            .map(|tm| tm.take_pattern().unwrap_or_else(|| unreachable!()))
    }

    /// Generates transitions from the model up to a specified size.
    ///
    /// For the definition of *transition*, see [`Net`].
    pub fn transitions(&self, max_rules: usize) -> impl Iterator<Item = RuleTm> {
        (1..=max_rules)
            .flat_map(|n| {
                chain(self.model.agent_names(), self.model.rule_names())
                    .combinations_with_replacement(n)
            })
            .filter(|names| names.iter().any(|name| self.model.has_rule(name)))
            .flat_map(|names| self.find(names))
            .map(|tm| tm.take_rule().unwrap_or_else(|| unreachable!()))
    }

    fn find(&self, generator_names: Vec<Name>) -> Vec<ModelTm> {
        // Collect all variables, then ensure they are unique.
        let (mut generator_sorts, mut variables) = (Vec::new(), Vec::new());
        for name in &generator_names {
            let interface = self.model.interface(name).unwrap().typed_vars();

            // Degenerate case: if a generator's interface is empty, exit early
            // since any non-trivial product with the generator is decomposable.
            if interface.is_empty() {
                return if generator_names.len() == 1 {
                    vec![ModelTm::basic(self.model, *name, vec![]).unwrap()]
                } else {
                    vec![]
                };
            }

            let (vars, sorts): (Vec<_>, Vec<_>) = interface.into_iter().unzip();
            generator_sorts.push(sorts);
            variables.extend(vars);
        }
        uniquify_names(&mut variables);

        // Build initial term.
        let mut terms = Vec::new();
        let mut interface = Vec::new();
        let mut variables = variables.into_iter();
        for (i, (name, sorts)) in zip_eq(generator_names, generator_sorts).enumerate() {
            let mut vars = Vec::new();
            for sort in sorts {
                let var = variables.next().unwrap();
                interface.push(IntermediateVar { name: var, sort, component: i });
                vars.push(MorTm::fvar(var));
            }
            terms.push(ModelTm::basic(self.model, name, vars).unwrap());
        }
        let n = terms.len();
        let tm = if n == 1 {
            terms.remove(0)
        } else {
            ModelTm::tensor(ModelTm::list(terms))
        };

        // Initialize the search state, then run the search.
        let state = SearchState {
            tm,
            interface,
            next_name: 0,
            uf: Rc::new(QuickUnionUf::new(n)),
            seen: Default::default(),
        };
        let mut results = Vec::new();
        self.recurse(state, &mut results);
        results
    }

    fn recurse(&self, state: SearchState, results: &mut Vec<ModelTm>) {
        let SearchState { interface, tm, next_name, uf, seen } = state;

        // Success condition: found a closed term.
        if interface.is_empty() {
            results.push(tm);
            return;
        }

        for idxs in (0..interface.len()).powerset() {
            // To avoid duplicate species, skip any matches that do not include
            // at least one free variable that has not already been seen.
            //
            // As a degenerate case, do not restrict along co-nullary operations
            // as that causes infinite blow-up. Such operations, which include
            // [scalars](https://ncatlab.org/nlab/show/monoidal+category#scalars),
            // also seem pointless, but perhaps they're good for something?
            if idxs.iter().all(|&i| seen.contains(&interface[i].name)) {
                continue;
            }

            // Get co-applicable operations, bailing early if there are none.
            let sorts = idxs.iter().map(|&i| interface[i].sort).collect_vec();
            let Some(operations) = self.cod_index.get(&sorts).filter(|ops| !ops.is_empty()) else {
                continue;
            };

            // Mark as seen all free variables up to the last matched variable
            // (unless they're already eliminated by the match).
            let mut seen = seen.clone();
            let last_idx = idxs.iter().max().unwrap();
            for (i, var) in interface.iter().enumerate().take(last_idx + 1) {
                if !idxs.contains(&i) {
                    seen.insert(var.name);
                }
            }

            // Union components involved in restricting along these indices.
            let mut uf = uf.clone();
            let mut has_merged = false;
            let mut components = idxs.iter().map(|&i| interface[i].component);
            let first = components.next().unwrap();
            for component in components {
                if Rc::make_mut(&mut uf).union(first, component) {
                    has_merged = true;
                }
            }
            let component = if has_merged {
                Rc::make_mut(&mut uf).find(first)
            } else {
                first
            };

            // Construct interface that remains after restricting along indices.
            let interface_kept = interface
                .iter()
                .enumerate()
                .filter_map(|(i, &(mut var))| {
                    if idxs.contains(&i) {
                        return None;
                    }
                    if has_merged {
                        var.component = Rc::make_mut(&mut uf).find(var.component);
                    }
                    Some(var)
                })
                .collect_vec();

            // Restrict along each co-applicable operation and recurse.
            for op in operations {
                let (dom, cod) = self.model.signature().interface(op).unwrap();

                let mut n = next_name;
                let mut interface_added = dom
                    .sorts()
                    .into_iter()
                    .map(|sort| {
                        let name = format!("x{n}").into();
                        n += 1;
                        IntermediateVar { name, sort, component }
                    })
                    .collect_vec();

                // If this component is being closed off but does not overlap
                // with the (non-trivial) remaining interface, then any further
                // pattern derived will be decomposable, so skip it.
                if interface_added.is_empty()
                    && !interface_kept.is_empty()
                    && interface_kept.iter().all(|var| var.component != component)
                {
                    continue;
                }

                let vars = idxs.iter().map(|&i| ObTm::var(interface[i].name));
                let restrict_at = if matches!(cod, Ty::Sort(_)) {
                    vars.exactly_one().unwrap()
                } else {
                    ObTm::tensor(ObTm::list(vars))
                };

                let args = MorTm::list(interface_added.iter().map(|var| MorTm::fvar(var.name)));
                let restrict_along = MorTm::app(*op, args);

                let mut interface = interface_kept.clone();
                interface.append(&mut interface_added);
                let state = SearchState {
                    tm: tm.restrict(restrict_at, restrict_along),
                    interface,
                    next_name: n,
                    uf: uf.clone(),
                    seen: seen.clone(),
                };
                self.recurse(state, results)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{super::model, super::theory::*, *};
    use expect_test::expect;

    #[test]
    fn toy_model_v1() {
        let model = model::toy_model_v1();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            A [unphos [], empty []]
            A [phos [], empty []]
            B [empty []]
            K []
            let bond [] in (A [unphos [], 0.0], A [unphos [], 0.1])
            let bond [] in (A [unphos [], 0.0], A [phos [], 0.1])
            let bond [] in (A [phos [], 0.0], A [unphos [], 0.1])
            let bond [] in (A [phos [], 0.0], A [phos [], 0.1])
            let bond [] in (A [unphos [], 0.0], B [0.1])
            let bond [] in (A [phos [], 0.0], B [0.1])
            let bond [] in (B [0.0], B [0.1])"#]];
        species.assert_eq(&generator.species(2).join("\n"));

        let transitions = expect![[r#"
            bondAB [unphos []]
              : (A [unphos [], empty []], B [empty []])
              → let bond [] in (A [unphos [], 0.0], B [0.1])
            bondAB [phos []]
              : (A [phos [], empty []], B [empty []])
              → let bond [] in (A [phos [], 0.0], B [0.1])
            phosphorylate [empty []]
              : (A [unphos [], empty []], K [])
              → (A [phos [], empty []], K [])
            let bond [] in (A [unphos [], 0.0], phosphorylate [0.1])
              : let bond [] in (A [unphos [], 0.0], (A [unphos [], 0.1], K []))
              → let bond [] in (A [unphos [], 0.0], (A [phos [], 0.1], K []))
            let bond [] in (A [phos [], 0.0], phosphorylate [0.1])
              : let bond [] in (A [phos [], 0.0], (A [unphos [], 0.1], K []))
              → let bond [] in (A [phos [], 0.0], (A [phos [], 0.1], K []))
            let bond [] in (B [0.0], phosphorylate [0.1])
              : let bond [] in (B [0.0], (A [unphos [], 0.1], K []))
              → let bond [] in (B [0.0], (A [phos [], 0.1], K []))
            let bond [] in (phosphorylate [0.0], phosphorylate [0.1])
              : let bond [] in ((A [unphos [], 0.0], K []), (A [unphos [], 0.1], K []))
              → let bond [] in ((A [phos [], 0.0], K []), (A [phos [], 0.1], K []))"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n"));
    }

    #[test]
    fn toy_model_v2() {
        let model = model::toy_model_v2();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            A [unphos [], emptyA []]
            A [phos [], emptyA []]
            B [emptyB []]
            K []
            let bond [] in (A [unphos [], 0.0], B [0.1])
            let bond [] in (A [phos [], 0.0], B [0.1])"#]];
        species.assert_eq(&generator.species(2).join("\n"));

        let transitions = expect![[r#"
            bondAB [unphos []]
              : (A [unphos [], emptyA []], B [emptyB []])
              → let bond [] in (A [unphos [], 0.0], B [0.1])
            bondAB [phos []]
              : (A [phos [], emptyA []], B [emptyB []])
              → let bond [] in (A [phos [], 0.0], B [0.1])
            phosphorylate [emptyA []]
              : (A [unphos [], emptyA []], K [])
              → (A [phos [], emptyA []], K [])
            let bond [] in (B [0.0], phosphorylate [0.1])
              : let bond [] in (B [0.0], (A [unphos [], 0.1], K []))
              → let bond [] in (B [0.0], (A [phos [], 0.1], K []))"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n"));

        // FIXME: Need to factorize with factors of length greater than one.
        //let net = expect![[r#""#]];
        //net.assert_eq(&generator.net(2).to_string());
    }

    #[test]
    fn expose_site() {
        type SigDecl = SignatureDecl;
        let sig = Signature::parse([
            SigDecl::sort("SiteA"),
            SigDecl::sort("SiteB"),
            SigDecl::sort("MaybeSiteB"),
            SigDecl::operation("noSite", [], Ty::sort("MaybeSiteB")),
            SigDecl::operation("hasSite", [Ty::sort("SiteB")], Ty::sort("MaybeSiteB")),
            SigDecl::operation("bond", [], Ty::tensor([Ty::sort("SiteA"), Ty::sort("SiteB")])),
        ])
        .unwrap();
        let decls = [
            ModelDecl::agent("A", [ObTm::var("s")], [Ty::sort("SiteA")]),
            ModelDecl::agent("B", [ObTm::var("s")], [Ty::sort("MaybeSiteB")]),
        ];
        let model = Model::parse(sig, decls).unwrap();

        let species = expect![[r#"
            B [noSite []]
            let bond [] in (A [0.0], B [hasSite [0.1]])"#]];
        species.assert_eq(&NetGenerator::new(&model).species(2).join("\n"));
    }
}
