//! Network generation from a rule-based model.

use derive_more::Unwrap;
use itertools::{chain, zip_eq};
use std::rc::Rc;
use union_find::{QuickUnionUf, UnionBySize, UnionFind};

use super::{core::*, model::*, net::*, ob_tm::*, prelude::*, ty::*};

/// Wrapper enum for the two kinds of terms in a model.
///
/// This enum exists because the algorithms to generate species or transitions
/// are essentially the same and thus can operate generically over this type
/// instead of being duplicated for each case.
#[derive(Clone, PartialEq, Eq, Unwrap)]
pub enum ModelTm {
    Pat(PatTm),
    Rule(RuleTm),
}

impl ModelTm {
    /// Constructs a model term corresponding to an agent or basic rule.
    fn basic(model: &Model, name: Name, terms: Vec<MorTm>) -> Option<Self> {
        if model.has_agent(&name) {
            Some(ModelTm::Pat(model.agent_tm(name, terms)))
        } else if model.has_rule(&name) {
            Some(ModelTm::Rule(model.rule_tm(name, terms)))
        } else {
            None
        }
    }

    /// Constructs an application of the tensor product to a model term.
    fn tensor(tm: ModelTm) -> Self {
        match tm {
            ModelTm::Pat(p) => ModelTm::Pat(PatTm::tensor(p)),
            ModelTm::Rule(r) => ModelTm::Rule(RuleTm::tensor(r)),
        }
    }

    /// Constructs a list of model terms.
    fn list(terms: impl IntoIterator<Item = ModelTm>) -> Self {
        let terms = terms.into_iter().collect_vec();
        if terms.iter().any(|tm| matches!(tm, ModelTm::Rule(_))) {
            // If any term is a rule, promote them all to rules.
            let rules = terms
                .into_iter()
                .map(|tm| match tm {
                    ModelTm::Rule(r) => r,
                    ModelTm::Pat(p) => RuleTm { rule: p.clone(), lhs: p.clone(), rhs: p },
                })
                .collect_vec();
            ModelTm::Rule(RuleTm::list(rules))
        } else {
            // Otherwise, we have a list of patterns.
            let patterns = terms.into_iter().map(|tm| tm.unwrap_pat());
            ModelTm::Pat(PatTm::list(patterns))
        }
    }

    /// Restricts the model term at free variables along a morphism term.
    fn restrict(&self, at: ObTm, along: MorTm) -> Self {
        match self {
            ModelTm::Pat(p) => ModelTm::Pat(p.clone().restrict(&at, along)),
            ModelTm::Rule(r) => ModelTm::Rule(r.clone().restrict(&at, along)),
        }
    }
}

/// Generates a reaction network from a rule-based model.
pub struct NetGenerator<'a> {
    /// Model to generate from.
    model: &'a Model,

    /// Index of co-applicable operations by their flattened codomains.
    ///
    /// Note that each operation is indexed on all unique permutations of the
    /// sorts comprising its flattened codomain.
    op_index: HashMap<Vec<Name>, Vec<OpIndexEntry>>,
}

/// An entry in the index of co-applicable operations.
struct OpIndexEntry {
    /// Name of operation.
    operation: Name,

    /// Permutation reordering the matched variables (given by the index key) to
    /// agree with the operation's codomain.
    permutation: Vec<usize>,
}

/// State maintained by search algorithm for network generation.
#[derive(Clone)]
struct SearchState {
    /// Current term.
    tm: ModelTm,

    /// Current list of free variables.
    interface: Vec<IntermediateVar>,

    /// Fresh variable names are generated by incrementing this counter.
    next_name: usize,

    /// Current partition of (indexes of) original list of free variables.
    ///
    /// Wrap the union find in `Rc` since we don't have to mutate it at each
    /// branch point, only when restricting along an operation of co-arity >= 2.
    uf: Rc<QuickUnionUf<UnionBySize>>,

    /// Set of free variables that have been seen but not substituted.
    seen: im::HashSet<Name>,
}

#[derive(Clone, Copy, Debug)]
struct IntermediateVar {
    name: Name,
    sort: Name,
    component: usize,
}

impl<'a> NetGenerator<'a> {
    /// Constructs a network generator for the given model.
    pub fn new(model: &'a Model) -> Self {
        let op_index = Self::build_op_index(model);
        Self { model, op_index }
    }

    /// Constructs the operation index for a model.
    fn build_op_index(model: &Model) -> HashMap<Vec<Name>, Vec<OpIndexEntry>> {
        let mut index = HashMap::<_, Vec<_>>::new();
        for (name, _, cod) in model.signature().operations() {
            let sorts = cod.sorts();
            let n = sorts.len();
            let mut seen = HashSet::new();
            for p in (0..n).permutations(n) {
                // Only store *unique* permutations of the sorts.
                let key = p.iter().map(|&i| sorts[i]).collect_vec();
                if seen.contains(&key) {
                    continue;
                }
                seen.insert(key.clone());

                // Need inverse permutation to order variables for binding.
                let mut p_inv = vec![0; n];
                for (j, pos) in p.into_iter().enumerate() {
                    p_inv[pos] = j;
                }
                index
                    .entry(key)
                    .or_default()
                    .push(OpIndexEntry { operation: name, permutation: p_inv });
            }
        }
        index
    }

    /// Generates a network from the model up to a specified size.
    pub fn net(&self, max_width: usize) -> Net {
        let (species, transitions): (Vec<_>, Vec<_>) = (1..=max_width)
            .flat_map(|n| {
                chain(self.model.agent_names(), self.model.rule_names())
                    .combinations_with_replacement(n)
            })
            .flat_map(|names| self.find(names))
            .partition_map(|tm| match tm {
                ModelTm::Pat(pat) => Either::Left(pat),
                ModelTm::Rule(rule) => Either::Right(rule),
            });

        let mut net = Net::new();
        for tm in species {
            net.add_species(tm.normalize());
        }
        for rule in transitions {
            let src = rule.lhs.normalize().factorize().collect_tensor();
            let tgt = rule.rhs.normalize().factorize().collect_tensor();
            net.add_transition(rule.rule, &src, &tgt)
                .map_err(|tm| tm.to_string())
                .expect("Species should already be added");
        }
        net
    }

    /// Generates species from the model up to a specified size.
    ///
    /// For definition of *species*, see [`Net`]. The resulting species are not
    /// necessarily in normal form.
    pub fn species(&self, max_agents: usize) -> impl Iterator<Item = PatTm> {
        (1..=max_agents)
            .flat_map(|n| self.model.agent_names().combinations_with_replacement(n))
            .flat_map(|agents| self.find(agents))
            .map(|tm| tm.unwrap_pat())
    }

    /// Generates transitions from the model up to a specified size.
    ///
    /// For the definition of *transition*, see [`Net`]. The resulting
    /// transitions are not necessarily in normal form.
    pub fn transitions(&self, max_rules: usize) -> impl Iterator<Item = RuleTm> {
        (1..=max_rules)
            .flat_map(|n| {
                chain(self.model.agent_names(), self.model.rule_names())
                    .combinations_with_replacement(n)
            })
            .filter(|names| names.iter().any(|name| self.model.has_rule(name)))
            .flat_map(|names| self.find(names))
            .map(|tm| tm.unwrap_rule())
    }

    fn find(&self, generator_names: Vec<Name>) -> Vec<ModelTm> {
        // Collect all variables, then ensure they are unique.
        let (mut generator_sorts, mut variables) = (Vec::new(), Vec::new());
        for name in &generator_names {
            let interface = self.model.interface(name).unwrap().typed_vars();

            // Degenerate case: if a generator's interface is empty, exit early
            // since any non-trivial product with the generator is decomposable.
            if interface.is_empty() {
                return if generator_names.len() == 1 {
                    vec![ModelTm::basic(self.model, *name, vec![]).unwrap()]
                } else {
                    vec![]
                };
            }

            let (vars, sorts): (Vec<_>, Vec<_>) = interface.into_iter().unzip();
            generator_sorts.push(sorts);
            variables.extend(vars);
        }
        uniquify_names(&mut variables);

        // Build initial term.
        let mut terms = Vec::new();
        let mut interface = Vec::new();
        let mut variables = variables.into_iter();
        for (i, (name, sorts)) in zip_eq(generator_names, generator_sorts).enumerate() {
            let mut vars = Vec::new();
            for sort in sorts {
                let var = variables.next().unwrap();
                interface.push(IntermediateVar { name: var, sort, component: i });
                vars.push(MorTm::fvar(var));
            }
            terms.push(ModelTm::basic(self.model, name, vars).unwrap());
        }
        let n = terms.len();
        let tm = if n == 1 {
            terms.remove(0)
        } else {
            ModelTm::tensor(ModelTm::list(terms))
        };

        // Initialize the search state, then run the search.
        let state = SearchState {
            tm,
            interface,
            next_name: 0,
            uf: Rc::new(QuickUnionUf::new(n)),
            seen: Default::default(),
        };
        let mut results = Vec::new();
        self.recurse(state, &mut results);
        results
    }

    fn recurse(&self, state: SearchState, results: &mut Vec<ModelTm>) {
        let SearchState { interface, tm, next_name, uf, seen } = state;

        // Success condition: found a closed term.
        if interface.is_empty() {
            results.push(tm);
            return;
        }

        for idxs in (0..interface.len()).powerset() {
            // To avoid duplicate species, skip any matches that do not include
            // at least one free variable that has not already been seen.
            //
            // As a degenerate case, do not restrict along co-nullary operations
            // as that causes infinite blow-up. Such operations, which include
            // [scalars](https://ncatlab.org/nlab/show/monoidal+category#scalars),
            // also seem pointless, but perhaps they're good for something?
            if idxs.iter().all(|&i| seen.contains(&interface[i].name)) {
                continue;
            }

            // Get co-applicable operations, bailing early if there are none.
            let sorts = idxs.iter().map(|&i| interface[i].sort).collect_vec();
            let Some(operations) = self.op_index.get(&sorts).filter(|ops| !ops.is_empty()) else {
                continue;
            };

            // Mark as seen all free variables up to the last matched variable
            // (unless they're already eliminated by the match).
            let mut seen = seen.clone();
            let last_idx = idxs.iter().max().unwrap();
            for (i, var) in interface.iter().enumerate().take(last_idx + 1) {
                if !idxs.contains(&i) {
                    seen.insert(var.name);
                }
            }

            // Union components involved in restricting along these indices.
            let mut uf = uf.clone();
            let mut has_merged = false;
            let mut components = idxs.iter().map(|&i| interface[i].component);
            let first = components.next().unwrap();
            for component in components {
                if Rc::make_mut(&mut uf).union(first, component) {
                    has_merged = true;
                }
            }
            let component = if has_merged {
                Rc::make_mut(&mut uf).find(first)
            } else {
                first
            };

            // Construct interface that remains after restricting along indices.
            let interface_kept = interface
                .iter()
                .enumerate()
                .filter_map(|(i, &(mut var))| {
                    if idxs.contains(&i) {
                        return None;
                    }
                    if has_merged {
                        var.component = Rc::make_mut(&mut uf).find(var.component);
                    }
                    Some(var)
                })
                .collect_vec();

            // Restrict along each co-applicable operation and recurse.
            for OpIndexEntry { operation: op, permutation: perm } in operations {
                let (dom, cod) = self.model.signature().interface(op).unwrap();

                let mut n = next_name;
                let mut interface_added = dom
                    .sorts()
                    .into_iter()
                    .map(|sort| {
                        let name = format!("x{n}").into();
                        n += 1;
                        IntermediateVar { name, sort, component }
                    })
                    .collect_vec();

                // If this component is being closed off but does not overlap
                // with the (non-trivial) remaining interface, then any further
                // pattern derived will be decomposable, so skip it.
                if interface_added.is_empty()
                    && !interface_kept.is_empty()
                    && interface_kept.iter().all(|var| var.component != component)
                {
                    continue;
                }

                // Reorder matched variables to align with operation's codomain.
                let vars = perm.iter().map(|&j| ObTm::var(interface[idxs[j]].name));
                let restrict_at = if matches!(cod, Ty::Sort(_)) {
                    vars.exactly_one().unwrap()
                } else {
                    ObTm::tensor(ObTm::list(vars))
                };

                let args = MorTm::list(interface_added.iter().map(|var| MorTm::fvar(var.name)));
                let restrict_along = MorTm::app(*op, args);

                let mut interface = interface_kept.clone();
                interface.append(&mut interface_added);
                let state = SearchState {
                    tm: tm.restrict(restrict_at, restrict_along),
                    interface,
                    next_name: n,
                    uf: uf.clone(),
                    seen: seen.clone(),
                };
                self.recurse(state, results)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{super::model, super::theory::*, *};
    use expect_test::expect;

    #[test]
    fn toy_model_v1() {
        let model = model::toy_model_v1();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            A [unphos [], empty []]
            A [phos [], empty []]
            B [empty []]
            K []
            let bond [] in (A [unphos [], 0.0], A [unphos [], 0.1])
            let bond [] in (A [unphos [], 0.0], A [phos [], 0.1])
            let bond [] in (A [phos [], 0.0], A [unphos [], 0.1])
            let bond [] in (A [phos [], 0.0], A [phos [], 0.1])
            let bond [] in (A [unphos [], 0.0], B [0.1])
            let bond [] in (A [phos [], 0.0], B [0.1])
            let bond [] in (B [0.0], B [0.1])"#]];
        species.assert_eq(&generator.species(2).join("\n"));

        let transitions = expect![[r#"
            bondAB [unphos []]
              : (A [unphos [], empty []], B [empty []])
              → let bond [] in (A [unphos [], 0.0], B [0.1])
            bondAB [phos []]
              : (A [phos [], empty []], B [empty []])
              → let bond [] in (A [phos [], 0.0], B [0.1])
            phosphorylate [empty []]
              : (A [unphos [], empty []], K [])
              → (A [phos [], empty []], K [])
            let bond [] in (A [unphos [], 0.0], phosphorylate [0.1])
              : let bond [] in (A [unphos [], 0.0], (A [unphos [], 0.1], K []))
              → let bond [] in (A [unphos [], 0.0], (A [phos [], 0.1], K []))
            let bond [] in (A [phos [], 0.0], phosphorylate [0.1])
              : let bond [] in (A [phos [], 0.0], (A [unphos [], 0.1], K []))
              → let bond [] in (A [phos [], 0.0], (A [phos [], 0.1], K []))
            let bond [] in (B [0.0], phosphorylate [0.1])
              : let bond [] in (B [0.0], (A [unphos [], 0.1], K []))
              → let bond [] in (B [0.0], (A [phos [], 0.1], K []))
            let bond [] in (phosphorylate [0.0], phosphorylate [0.1])
              : let bond [] in ((A [unphos [], 0.0], K []), (A [unphos [], 0.1], K []))
              → let bond [] in ((A [phos [], 0.0], K []), (A [phos [], 0.1], K []))"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n"));
    }

    #[test]
    fn toy_model_v2() {
        let model = model::toy_model_v2();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            A [unphos [], emptyA []]
            A [phos [], emptyA []]
            B [emptyB []]
            K []
            let bond [] in (A [unphos [], 0.0], B [0.1])
            let bond [] in (A [phos [], 0.0], B [0.1])"#]];
        species.assert_eq(&generator.species(2).join("\n"));

        let transitions = expect![[r#"
            bondAB [unphos []]
              : (A [unphos [], emptyA []], B [emptyB []])
              → let bond [] in (A [unphos [], 0.0], B [0.1])
            bondAB [phos []]
              : (A [phos [], emptyA []], B [emptyB []])
              → let bond [] in (A [phos [], 0.0], B [0.1])
            phosphorylate [emptyA []]
              : (A [unphos [], emptyA []], K [])
              → (A [phos [], emptyA []], K [])
            let bond [] in (B [0.1], phosphorylate [0.0])
              : let bond [] in (B [0.1], (A [unphos [], 0.0], K []))
              → let bond [] in (B [0.1], (A [phos [], 0.0], K []))"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n"));

        let net = expect![[r#"
            #/ species:
            A [unphos [], emptyA []]
            A [phos [], emptyA []]
            B [emptyB []]
            K []
            let bond [] in (A [unphos [], 0.0], B [0.1])
            let bond [] in (A [phos [], 0.0], B [0.1])
            #/ transitions:
            bondAB [unphos []]
              : [A [unphos [], emptyA []], B [emptyB []]]
              → [let bond [] in (A [unphos [], 0.0], B [0.1])]
            bondAB [phos []]
              : [A [phos [], emptyA []], B [emptyB []]]
              → [let bond [] in (A [phos [], 0.0], B [0.1])]
            phosphorylate [emptyA []]
              : [A [unphos [], emptyA []], K []]
              → [A [phos [], emptyA []], K []]
            let bond [] in (B [0.1], phosphorylate [0.0])
              : [let bond [] in (A [unphos [], 0.0], B [0.1]), K []]
              → [let bond [] in (A [phos [], 0.0], B [0.1]), K []]
        "#]];
        net.assert_eq(&generator.net(2).to_string());
    }

    #[test]
    fn expose_site() {
        type SigDecl = SignatureDecl;
        let sig = Signature::parse([
            SigDecl::sort("SiteA"),
            SigDecl::sort("SiteB"),
            SigDecl::sort("MaybeSiteB"),
            SigDecl::operation("noSite", [], Ty::sort("MaybeSiteB")),
            SigDecl::operation("hasSite", [Ty::sort("SiteB")], Ty::sort("MaybeSiteB")),
            SigDecl::operation("bond", [], Ty::tensor([Ty::sort("SiteA"), Ty::sort("SiteB")])),
        ])
        .unwrap();
        let decls = [
            ModelDecl::agent("A", [ObTm::var("s")], [Ty::sort("SiteA")]),
            ModelDecl::agent("B", [ObTm::var("s")], [Ty::sort("MaybeSiteB")]),
        ];
        let model = Model::parse(sig, decls).unwrap();

        let species = expect![[r#"
            B [noSite []]
            let bond [] in (A [0.0], B [hasSite [0.1]])"#]];
        species.assert_eq(&NetGenerator::new(&model).species(2).join("\n"));
    }

    #[test]
    fn toy_model_species_granularity_1() {
        let model = model::toy_model_species_granularity_1();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            M [iota_A [ground_A []]]
            M [iota_B [ground_B []]]
            M [iota_K [ground_K []]]
            M [iota_SiteA [emptyA []]]
            M [iota_SiteB [emptyB []]]
            M [iota_Res [phos []]]
            M [iota_Res [unphos []]]
            let bond [] in (M [iota_SiteA [0.0]], M [iota_SiteB [0.1]])
            let bond [] in (M [iota_SiteB [0.1]], M [iota_SiteA [0.0]])"#]];
        species.assert_eq(&generator.species(2).join("\n"));

        let transitions = expect![[r#"
            bondAB [ground_B [], phos []]
              : (
                (M [iota_A], M [iota_SiteB empty []], M [iota_Res phos []]),
                (M [iota_B b []], M [iota_SiteA empty []])
              )
              → let bond [] in
                (
                  (M [iota_A], M [iota_SiteB 0.1], M [iota_Res phos []]),
                  (M [iota_B b []], M [iota_SiteA 0.0])
                )
            bondAB [ground_B [], unphos []]
              : (
                (M [iota_A], M [iota_SiteB empty []], M [iota_Res unphos []]),
                (M [iota_B b []], M [iota_SiteA empty []])
              )
              → let bond [] in
                (
                  (M [iota_A], M [iota_SiteB 0.1], M [iota_Res unphos []]),
                  (M [iota_B b []], M [iota_SiteA 0.0])
                )
            phosphorylate [emptyB []]
              : (
                (M [iota_A], M [iota_SiteB emptyB []], M [iota_Res unphos []]),
                (M [iota_K])
              )
              → ((M [iota_A], M [iota_SiteB emptyB []], M [iota_Res phos []]), (M [iota_K]))
            let bond [] in (M [iota_SiteA [0.0]], phosphorylate [0.1])
              : let bond [] in
                (
                  M [iota_SiteA [0.0]],
                  ((M [iota_A], M [iota_SiteB 0.1], M [iota_Res unphos []]), (M [iota_K]))
                )
              → let bond [] in
                (
                  M [iota_SiteA [0.0]],
                  ((M [iota_A], M [iota_SiteB 0.1], M [iota_Res phos []]), (M [iota_K]))
                )"#]]; // Note that 
        transitions.assert_eq(&generator.transitions(2).join("\n"));
    }
    // The algorithm is doing what it is supposed to, but for the RHS of the rule I actually intended M [iota_B] to be present:
    // let bond [] in
    // (
    // (M [iota_B], M [iota_SiteA [0.0]]),
    // ((M [iota_A], M [iota_SiteB 0.1], M [iota_Res phos []]), (M [iota_K]))
    // )

    #[test]
    fn toy_model_species_granularity_2() {
        let model = model::toy_model_species_granularity_2();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            M [iota_A [ground_A []]]
            M [iota_B [iota_B1 [ground_B1 []]]]
            M [iota_B [iota_B2 [ground_B2 []]]]
            M [iota_K [ground_K []]]
            M [iota_SiteA [emptyA []]]
            M [iota_SiteB [emptyB []]]
            M [iota_Res [phos []]]
            M [iota_Res [unphos []]]
            let bond [] in (M [iota_SiteA [0.0]], M [iota_SiteB [0.1]])
            let bond [] in (M [iota_SiteB [0.1]], M [iota_SiteA [0.0]])"#]];
        species.assert_eq(&generator.species(2).join("\n"));

        let transitions = expect![[r#"
            bondAB [iota_B1 [ground_B1 []], phos []]
              : (
                (M [iota_A], M [iota_SiteB empty []], M [iota_Res phos []]),
                (M [iota_B b []], M [iota_SiteA empty []])
              )
              → let bond [] in
                (
                  (M [iota_A], M [iota_SiteB 0.1], M [iota_Res phos []]),
                  (M [iota_B b []], M [iota_SiteA 0.0])
                )
            bondAB [iota_B1 [ground_B1 []], unphos []]
              : (
                (M [iota_A], M [iota_SiteB empty []], M [iota_Res unphos []]),
                (M [iota_B b []], M [iota_SiteA empty []])
              )
              → let bond [] in
                (
                  (M [iota_A], M [iota_SiteB 0.1], M [iota_Res unphos []]),
                  (M [iota_B b []], M [iota_SiteA 0.0])
                )
            bondAB [iota_B2 [ground_B2 []], phos []]
              : (
                (M [iota_A], M [iota_SiteB empty []], M [iota_Res phos []]),
                (M [iota_B b []], M [iota_SiteA empty []])
              )
              → let bond [] in
                (
                  (M [iota_A], M [iota_SiteB 0.1], M [iota_Res phos []]),
                  (M [iota_B b []], M [iota_SiteA 0.0])
                )
            bondAB [iota_B2 [ground_B2 []], unphos []]
              : (
                (M [iota_A], M [iota_SiteB empty []], M [iota_Res unphos []]),
                (M [iota_B b []], M [iota_SiteA empty []])
              )
              → let bond [] in
                (
                  (M [iota_A], M [iota_SiteB 0.1], M [iota_Res unphos []]),
                  (M [iota_B b []], M [iota_SiteA 0.0])
                )
            phosphorylate [emptyB []]
              : (
                (M [iota_A], M [iota_SiteB emptyB []], M [iota_Res unphos []]),
                (M [iota_K])
              )
              → ((M [iota_A], M [iota_SiteB emptyB []], M [iota_Res phos []]), (M [iota_K]))
            let bond [] in (M [iota_SiteA [0.0]], phosphorylate [0.1])
              : let bond [] in
                (
                  M [iota_SiteA [0.0]],
                  ((M [iota_A], M [iota_SiteB 0.1], M [iota_Res unphos []]), (M [iota_K]))
                )
              → let bond [] in
                (
                  M [iota_SiteA [0.0]],
                  ((M [iota_A], M [iota_SiteB 0.1], M [iota_Res phos []]), (M [iota_K]))
                )"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n"));
    }

    // TODO: Try to rewrite this model without generating unexpected species.
    #[test]
    fn toy_model_emergent_agent() {
        let model = model::toy_model_emergent_agent();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            A [e_B [], e_C []]
            B [e_A [], e_C []]
            C [e_AB [], e_AB []]
            let bond_AB [] in (A [0.1, e_C []], B [0.0, e_C []])
            let bond_C [] in (A [e_B [], 0.1], C [e_AB [], 0.0])
            let bond_C [] in (A [e_B [], 0.1], C [0.0, e_AB []])
            let bond_C [] in (B [e_A [], 0.1], C [e_AB [], 0.0])
            let bond_C [] in (B [e_A [], 0.1], C [0.0, e_AB []])
            let bond_C [] in
              let bond_C [] in (A [e_B [], 0.1], A [e_B [], 1.1], C [0.0, 1.0])
            let bond_C [] in
              let bond_C [] in (A [e_B [], 1.1], A [e_B [], 0.1], C [0.0, 1.0])
            let bond_C [] in
              let bond_C [] in (A [e_B [], 0.1], B [e_A [], 1.1], C [0.0, 1.0])
            let bond_C [] in
              let bond_C [] in (A [e_B [], 1.1], B [e_A [], 0.1], C [0.0, 1.0])
            let bond_C [] in
              let bond_AB [] in (A [0.1, e_C []], B [0.0, 1.1], C [e_AB [], 1.0])
            let bond_C [] in
              let bond_AB [] in (A [0.1, e_C []], B [0.0, 1.1], C [1.0, e_AB []])
            let bond_C [] in
              let bond_AB [] in (A [0.1, 1.1], B [0.0, e_C []], C [e_AB [], 1.0])
            let bond_C [] in
              let bond_AB [] in (A [0.1, 1.1], B [0.0, e_C []], C [1.0, e_AB []])
            let bond_C [] in
              let bond_C [] in let bond_AB [] in (A [0.1, 1.1], B [0.0, 2.1], C [1.0, 2.0])
            let bond_C [] in
              let bond_C [] in let bond_AB [] in (A [0.1, 2.1], B [0.0, 1.1], C [1.0, 2.0])
            let bond_C [] in
              let bond_C [] in (B [e_A [], 0.1], B [e_A [], 1.1], C [0.0, 1.0])
            let bond_C [] in
              let bond_C [] in (B [e_A [], 1.1], B [e_A [], 0.1], C [0.0, 1.0])"#]];
        species.assert_eq(&generator.species(3).join("\n"));

        let transitions = expect![[r#"
            R_dimerization [e_C [], e_C []]
              : (A [e_B], B [e_A])
              → let bond [] in (A [0.0, e_C], B [0.1, e_C])
            R_trimerization []
              : (let bond [] in (A [0.0, e_C], B [0.1, e_C]), C [e_AB, e_AB])
              → let bond [] in
                let bond [] in (let bond [] in (A [0.0, c], B [0.1, c]), C [0.1, 1.1])
            let bond_C [] in (C [e_AB [], 0.0], R_dimerization [e_C [], 0.1])
              : let bond_C [] in (C [e_AB [], 0.0], (A [e_B], B [e_A]))
              → let bond_C [] in
                (C [e_AB [], 0.0], let bond [] in (A [0.0, e_C], B [0.1, e_C]))
            let bond_C [] in (C [e_AB [], 0.0], R_dimerization [0.1, e_C []])
              : let bond_C [] in (C [e_AB [], 0.0], (A [e_B], B [e_A]))
              → let bond_C [] in
                (C [e_AB [], 0.0], let bond [] in (A [0.0, e_C], B [0.1, e_C]))
            let bond_C [] in (C [0.0, e_AB []], R_dimerization [e_C [], 0.1])
              : let bond_C [] in (C [0.0, e_AB []], (A [e_B], B [e_A]))
              → let bond_C [] in
                (C [0.0, e_AB []], let bond [] in (A [0.0, e_C], B [0.1, e_C]))
            let bond_C [] in (C [0.0, e_AB []], R_dimerization [0.1, e_C []])
              : let bond_C [] in (C [0.0, e_AB []], (A [e_B], B [e_A]))
              → let bond_C [] in
                (C [0.0, e_AB []], let bond [] in (A [0.0, e_C], B [0.1, e_C]))
            let bond_C [] in let bond_C [] in (C [0.0, 1.0], R_dimerization [0.1, 1.1])
              : let bond_C [] in let bond_C [] in (C [0.0, 1.0], (A [e_B], B [e_A]))
              → let bond_C [] in
                let bond_C [] in (C [0.0, 1.0], let bond [] in (A [0.0, e_C], B [0.1, e_C]))
            let bond_C [] in let bond_C [] in (C [1.0, 0.0], R_dimerization [0.1, 1.1])
              : let bond_C [] in let bond_C [] in (C [1.0, 0.0], (A [e_B], B [e_A]))
              → let bond_C [] in
                let bond_C [] in (C [1.0, 0.0], let bond [] in (A [0.0, e_C], B [0.1, e_C]))"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n")); // TODO: consider stronger typing to avoid explosion of transitions
    }

    // TODO: Try to rewrite this model without generating unexpected species.
    #[test]
    fn toy_model_directionality() {
        let model = model::toy_model_directionality();
        let generator = NetGenerator::new(&model);

        // @Evan: This shows the problem that the C is bound to the wrong A. It should be boud to the B-bound.
        // let bond [] in
        // let bond_AB [] in
        // (
        // A [e_ha [], e_Ca [], 0.0],
        // A [e_ha [], 1.1, e_ta []],
        // B [0.1, 1.2, e_tb []],
        // C [1.0]
        // )
        let species = expect![[r#"
            A [e_ha [], e_Ca [], e_ta []]
            B [e_hb [], e_Cb [], e_tb []]
            C [e_AB []]
            let bond_AB [] in (A [e_ha [], e_Ca [], 0.0], B [0.1, e_Cb [], e_tb []])
            let bond [] in (A [e_ha [], 0.1, e_ta []], B [e_hb [], 0.2, e_tb []], C [0.0])
            let bond [] in
              let bond_AB [] in (A [e_ha [], 1.1, 0.0], B [0.1, 1.2, e_tb []], C [1.0])
            let bond [] in
              let bond_AB [] in
                (
                  A [e_ha [], e_Ca [], 0.0],
                  A [e_ha [], 1.1, e_ta []],
                  B [0.1, 1.2, e_tb []],
                  C [1.0]
                )
            let bond [] in
              let bond_AB [] in
                (
                  A [e_ha [], 1.1, e_ta []],
                  A [e_ha [], e_Ca [], 0.0],
                  B [0.1, 1.2, e_tb []],
                  C [1.0]
                )
            let bond [] in
              let bond_AB [] in
                (
                  A [e_ha [], 1.1, 0.0],
                  B [e_hb [], 1.2, e_tb []],
                  B [0.1, e_Cb [], e_tb []],
                  C [1.0]
                )
            let bond [] in
              let bond_AB [] in
                (
                  A [e_ha [], 1.1, 0.0],
                  B [0.1, e_Cb [], e_tb []],
                  B [e_hb [], 1.2, e_tb []],
                  C [1.0]
                )"#]];
        species.assert_eq(&generator.species(4).join("\n")); // Note that this model allows infinite polymerization

        let transitions = expect![[r#"
            R_AtoB_dimerization [e_ha [], e_Ca [], e_Cb [], e_ta []]
              : (A [e_ha [], e_Ca [], e_t], B [e_h, e_Cb [], e_ta []])
              → let bond_AB [] in (A [e_ha [], e_Ca [], 0.0], B [0.1, e_Cb [], e_ta []])
            R_trimerization [e_ha [], e_tb []]
              : (
                let bond_AB [] in (A [e_ha [], e_Ca, 0.0], B [0.1, e_Cb, e_tb []]),
                C [e_AB]
              )
              → let bond [] in
                let bond_AB [] in (A [e_ha [], 1.0, 0.0], B [0.1, 1.1, e_tb []], C [1.2])
            let bond_AB [] in
                (
                  B [0.1, e_Cb [], e_tb []],
                  R_AtoB_dimerization [e_ha [], e_Ca [], e_Cb [], 0.0]
                )
              : let bond_AB [] in
                (
                  B [0.1, e_Cb [], e_tb []],
                  (A [e_ha [], e_Ca [], e_t], B [e_h, e_Cb [], 0.0])
                )
              → let bond_AB [] in
                (
                  B [0.1, e_Cb [], e_tb []],
                  let bond_AB [] in (A [e_ha [], e_Ca [], 0.0], B [0.1, e_Cb [], 1.0])
                )
            let bond [] in (C [0.0], R_AtoB_dimerization [e_ha [], 0.1, 0.2, e_ta []])
              : let bond [] in (C [0.0], (A [e_ha [], 0.1, e_t], B [e_h, 0.2, e_ta []]))
              → let bond [] in
                (C [0.0], let bond_AB [] in (A [e_ha [], 1.1, 0.0], B [0.1, 1.2, e_ta []]))"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n")); // TODO: consider stronger typing to avoid explosion of transitions
    }

    #[test]
    fn toy_model_phospho_tyrosine() {
        let model = model::toy_model_phospho_tyrosine();
        let generator = NetGenerator::new(&model);

        let species = expect![[r#"
            A [e_sh2 []]
            C [u [e_xtyr []]]
            C [p [e_xtyr []]]
            let bond [] in (A [0.0], C [u [0.1]])
            let bond [] in (A [0.0], C [p [0.1]])"#]];
        species.assert_eq(&generator.species(4).join("\n"));

        let transitions = expect![[r#"
            R_phosphorylation [] : A [u e_xtyr] → A [p e_xtyr]
            R_dimerization []
              : (A [e_sh2], C [p e_xtyr])
              → let bond [] in (A [0.0], C [p 0.1])"#]];
        transitions.assert_eq(&generator.transitions(2).join("\n")); // TODO: consider stronger typing to avoid explosion of transitions
    }
}
